# - Try to find Csound -
#
# Once done, this will define
# 
#   Csound_FOUND           - System has Csound
#   Csound_INCLUDE_DIRS    - Where to find csound.h
#   Csound_LIBRARIES       - Libraries to link
#   Csound::Csound         - Imported target
#
# Skeleton generated by ChatGPT. Let's keep the fingers crossed, that
# it is actually working. :-)

# Allow hinting via CSOUND_DIR
set(_CSOUND_HINTS
    ${CSOUND_DIR}
    ENV CSOUND_DIR
    "C:/Program Files/Csound6_x64"
    "C:/Program Files/Csound7_x64"
    "/usr"
    "/usr/local"
    "/opt/csound"
)

find_path(Csound_INCLUDE_DIR
    NAMES csound/csound.h
    HINTS ${_CSOUND_HINTS}
    PATH_SUFFIXES include include/csound
)

find_library(Csound_LIBRARY
    NAMES csound64 csound
    HINTS ${_CSOUND_HINTS}
    PATH_SUFFIXES lib build/lib
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Csound
    REQUIRED_VARS Csound_LIBRARY Csound_INCLUDE_DIR
)

if(Csound_FOUND)
    set(Csound_INCLUDE_DIRS ${Csound_INCLUDE_DIR})
    set(Csound_LIBRARIES ${Csound_LIBRARY})
    
    if(NOT TARGET Csound::Csound)
        add_library(Csound::Csound UNKNOWN IMPORTED)
        set_target_properties(Csound::Csound PROPERTIES
            IMPORTED_LOCATION "${Csound_LIBRARY}"
            INTERFACE_INCLUDE_DIRECTORIES "${Csound_INCLUDE_DIR}"
        )
    endif()
endif()
